name: "Terraform"

on:
  push:
    branches: ["main"]
  pull_request:

env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}

jobs:
  terraform-validate:
    name: "Terraform validate"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform validate
        run: terraform validate

  terraform-plan:
    needs: terraform-validate
    name: "Terraform plan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1    
      - name: Terraform Init
        run: terraform init  
      - name: Terraform Plan
        run: terraform plan -out=terraform.plan
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: terraform.plan

  terraform-apply:
    needs: terraform-plan
    name: "Terraform apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1      
      - name: Terraform Init
        run: terraform init
      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: .
      - name: Terraform Apply
        run: terraform apply  -auto-approve terraform.plan