name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable     
    - name: Restore dependencies
      run:  dotnet restore SeleniumBasicExercise.sln
    - name: Build the app
      run:  dotnet build SeleniumBasicExercise.sln --no-restore

  test:

    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable     
    - name: Restore dependencies
      run:  dotnet restore SeleniumBasicExercise.sln
    - name: Build the app
      run:  dotnet build SeleniumBasicExercise.sln --no-restore
    - name: Run UI tests for Project1
      env: 
        CHROMEWEBBROUSER: /usr/bin/google-chrome
      run:  |  
        echo "Run tests for Project1"
        dotnet test TestProject1/TestProject1.csproj --verbosity normal
    - name: Run UI tests for Project2
      env: 
        CHROMEWEBBROUSER: /usr/bin/google-chrome
      run:  |  
        echo "Run tests for Project2"
        dotnet test TestProject2/TestProject2.csproj --verbosity normal
    - name: Run UI tests for Project3
      env: 
        CHROMEWEBBROUSER: /usr/bin/google-chrome
      run:  |  
        echo "Run tests for Project3"
        dotnet test TestProject3/TestProject3.csproj --verbosity normal
