name: Build, Test and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Update the config
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js  
    - name: Start BE 
      run: npm run server &
    - name: Start FE 
      run: npm run start &
    - name: Install PlayWright
      run:  npx playwright install    
    - name: Run the UI tests
      run: npm run test

  deploy_BE:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
    - uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID_BE }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true

  deploy_FE:
    runs-on: ubuntu-latest
    needs: deploy_BE
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID_FE }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
      
    
   
