services:
  mongo:
    container_name: mongodb
    networks:
      - movies
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    image: mongo
  movies-be:
    container_name: backend
    networks:
      - movies
    ports:
      - 80:80
    volumes:
      - logs:/logs
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=password
    build: ./backend
  movies-fe:
    container_name: frontend
    networks:
      - movies
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/backend/src
    build: ./frontend
networks:
  movies:
    name: movies
volumes:
  data:
    name: data
  logs:
    name: logs
